server:
  port: 8349
#spring:
 # cloud:
  #####    predicates:
       #     - Path=/printers/*
#
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG